### ISSUE TITLE
Several modules missing

### ISSUE THREAD

**Issue by glennsl** [BuckleScript/bucklescript-playground#2]
```ml
let _ = Js.Promise.resolve 42
```
errors with
```
Line 1, 8: Unbound value Js.Promise.resolve
```

Missing modules uncovered so far:
* `Js.Promise`
* `Js.Json`
* `Js.Option`
* `Js.Float`

**Comment by glennsl** [comment]
`Js.Json` also seems to be missing in action

**Comment by glennsl** [comment]
`Js.Option` is missing too...

**Comment by bobzhang** [comment]
fixed
