### ISSUE TITLE
Missing module Js.Exn

### ISSUE THREAD

**Issue by glennsl** [BuckleScript/bucklescript-playground#3]

**Comment by glennsl** [comment]
@bobzhang I tried adding it and building it by running `repl.js` myself, but the build process seems to be pretty tailored to your environment. At least it's heavily broken in mine.

**Comment by anmonteiro** [comment]
addressed in https://github.com/BuckleScript/bucklescript/pull/1965

**Comment by bobzhang** [comment]
fixed
