### ISSUE TITLE
Curry.cmj corrupted in database

### ISSUE THREAD

**Issue by Schmavery** [BuckleScript/bucklescript-playground#5]
Getting `WARN: File "js_cmj_load.ml", line 45, characters 27-34 Curry.cmj corrupted in database, when looking curry.cmj while compiling please update` when trying to use https://reasonml.github.io/try

Example: `let foo (bar:int => int) => bar 1;`

https://reasonml.github.io/try/?reason=DYUwLgBAZg9jEAoBGBDATgLgJYDtIF4A+CXMASgiIlTQgEYBuIA

**Comment by chenglou** [comment]
@glennsl is this some staleness problem or something?

**Comment by glennsl** [comment]
I think so. It was built cleanly, but maybe there are some things included that aren't part of the usual build process. I'm trying to build everything from scratch now, but there's... difficulties...

**Comment by glennsl** [comment]
Ok, I came through it alive! Still don't know why these warnings occurred, but the above PRs seem to fix it.
