### ISSUE TITLE
Upgrade to the latest BuckleScript: 2.1.0

### ISSUE THREAD

**Issue by vietlq** [BuckleScript/bucklescript-playground#8]
Upgrade to the latest BuckleScript: 2.1.0

Some examples don't work with the version 1.9.x, say the basic example:

```
Js.log({js|你好，
世界|js});
```

**Comment by glennsl** [comment]
I've updated to 2.1.0, but quoted unicode strings have been around since 1.5.1. I think this might just be a limitation of the browser environment, or how the playground or compiler uses that environment.

**Comment by bobzhang** [comment]
should be done
